#pragma once

#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <iterator>
#include <memory>
#include <set>
#include <stdexcept>
#include <string>
#include <time.h>
#include <typeindex>
#include <typeinfo>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include <QBrush>
#include <QColor>
#include <QDebug>
#include <QFont>
#include <QGraphicsItem>
#include <QGraphicsOpacityEffect>
#include <QGraphicsPixmapItem>
#include <QGraphicsPolygonItem>
#include <QGraphicsRectItem>
#include <QGraphicsScene>
#include <QGraphicsSceneMouseEvent>
#include <QGraphicsSimpleTextItem>
#include <QGraphicsTextItem>
#include <QGraphicsView>
#include <QImage>
#include <QLine>
#include <QLineF>
#include <QMediaPlayer>
#include <QMetaType>
#include <QMouseEvent>
#include <QObject>
#include <QPen>
#include <QPixmap>
#include <QPoint>
#include <QPointF>
#include <QPointer>
#include <QPolygonF>
#include <QRectF>
#include <QSize>
#include <QSizeF>
#include <QThread>
#include <QTimer>
#include <QtGlobal>
#include <QtMath>
